# redis-master-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master
  labels:
    app: redis
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: master
  template:
    metadata:
      labels:
        app: redis
        role: master
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        command: ["redis-server"]
        args: ["--requirepass", "yourpassword"] # Optional: secure with a password

---
apiVersion: v1
kind: Service
metadata:
  name: redis-master-service
spec:
  selector:
    app: redis
    role: master
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP
  
  
---
 
 # redis-slave-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  labels:
    app: redis
    role: slave
spec:
  replicas: 1 # Adjust number of slaves as needed
  selector:
    matchLabels:
      app: redis
      role: slave
  template:
    metadata:
      labels:
        app: redis
        role: slave
    spec:
      containers:
      - name: redis
        image: redis:latest
        ports:
        - containerPort: 6379
        command: ["redis-server"]
        args: ["--slaveof", "redis-master-service", "6379", "--requirepass", "yourpassword", "--masterauth", "yourpassword"] # Connects to master
---
apiVersion: v1
kind: Service
metadata:
  name: redis-slave-service
spec:
  selector:
    app: redis
    role: slave
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP